### ISSUE TITLE
Censored cases Piñera's second government

### ISSUE THREAD

**Issue by bgonzalezbustamante** [bgonzalezbustamante/chilean-undersecretaries#33]
March 2022

**Comment by bgonzalezbustamante** [comment]
@janolivares estos 39 casos no tienen valores en la fecha de salida, por tanto, debiesen hasta hoy continuar en su cargo. Si no hay movimientos deberíamos censurarlos con la fecha de fin de gobierno. Avísame y puedo hacerlo de inmediato para actualizar y liberar la versión de la base de datos.

| name | undersec |
|---|---|
| Julio Pertuzé Salas | Economía |
| José Pinochet Olave | Agricultura |
| Álvaro Pillado Irribarra | Bienes Nacionales |
| Juan Carlos Silva Aldunate | Cultura |
| Cristián de la Maza Riquelme | Defensa |
| Andrés Otero Klein | Deportes |
| Jorge Poblete Aedo | Educación |
| Juan Eduardo Vargas Duhart | Educación Superior |
| Francisco Javier López Díaz | Energía |
| Alfonso Vargas Lyng | Fuerzas Armadas |
| Alejandro Weber Pérez  | Hacienda |
| Juan Francisco Galli Basili | Interior |
| Sebastián Valenzuela Agüero | Justicia |
| Javier Naranjo Solano | Medio Ambiente |
| Edgar Blanco Rand | Minería |
| Cristóbal Leturia Infante | Obras Públicas |
| Emilio de la Cerda Errázuriz | Patrimonio Cultural |
| Pedro Pizarro Cañas | Previsión Social |
| Alberto Dougnac Labatut | Redes Asistenciales |
| Rodrigo Yáñez Benítez | Relaciones Económicas |
| Emardo Hantelmann Godoy | SEGEGOB |
| Máximo Pavez Cantillano | SEGPRES |
| Fernando Arab Verdugo | Trabajo |
| José Luis Domínguez Covarrubias | Transporte |
| José Luis Uriarte Campos | Turismo |
| Guillermo Rolando Vicente | Vivienda |
| Carolina Torrealba Ruiz-Tagle | Ciencia, Tecnología, Conocimiento e Innovación |
| Lorena Recabarren Silva | Derechos Humanos |
| María Jesús Honorato Errázuriz | Educación Parvularia |
| María José Abud Sittler | Mujer y Equidad de Género |
| Alejandra Candia Díaz | Evaluación Social |
| Blanquita Honorato Lira  | Niñez |
| Alicia Gallardo Lagno | Pesca |
| María José Gómez | Prevención del Delito |
| Carolina Valdivia Torres | Relaciones Exteriores |
| María Paz Troncoso Pulgar | SUBDERE |
| Pamela Gidi Masías | Telecomunicaciones |
| Andrea Balladares | Servicos Sociales |
| María Teresa Valenzuela | Salud |

**Comment by janolivares** [comment]
Juan Francisco Galli Basili dejo el cargo el 9/mar/2022
Carolina Valdivia Torres dejo el cargo el 06/feb/2022
Gloria Navarrete Pinto asumió como subse subrogante de Relaciones Exteriores entre 06/feb/2022 y 11/mar/2022 (no milita)
Pamela Gidi Masías dejo el cargo el 09/jun/2021 (Es EVOPOLI) 
Francisco Moreno Guzmán asumió subse de Telecomunicaciones el 09/jun/2021 hasta 11/03/2022 milita en la UDI


--


<br class="Apple-interchange-newline">
</body>
</html>
